language: python

python:
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install codecov
  - pip install .

before_script:
  - sudo apt-get install libnl-genl-3-dev
  - gcc $(pkg-config --cflags --libs libnl-genl-3.0) tests/linux_private/correct_answers.c
  - ./a.out > tests/correct_answers.json

script:
  - python setup.py test

after_success: codecov
