language: python

python:
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install codecov docopt

script:
  - python setup.py test

after_success: codecov
